# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15312fed53e777a3e3ca97ba7f8d88311b972dc8e4c83acc0245a58f1b8ae00ff581f7d162d5efc46183b4827a0c1be1593290e3beb02e7f8aff419e85d74ca

test:
  secret_key_base: 1ef3efc23480906111f0d9f0ae1171f3b85ecbdc03877cea1369bf2b6be16ed62023d6d731a80fb5237a4a985b1b54c6b9a27e43c716fd9fba8bdc677d8f991c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
